# Generated by Django 3.1.5 on 2021-01-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_auto_20210130_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_01.logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(default='default.png', upload_to='logo/', verbose_name='Logo'),
        ),
    ]
